# Generated by Django 5.0.2 on 2024-03-05 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choiice',
            new_name='Choice',
        ),
    ]
